### ISSUE TITLE
missing onTap callback?

### ISSUE THREAD

**Issue by robandrose** [FormidableLabs/react-swipeable#139]
why did you skip the onTap callback in version 5? Is there an easy way to create the onTap functionality, when dragging didn't take place?

**Comment by hartzis** [comment]
@robandrose Great question. To be honest, didn't really think anyone was using it, lol.

I think we can recreate it.

Try this out and let me know if it will work for your use case.

https://codesandbox.io/s/ly2z147l4z

Setting the `delta` to 0, the "swipe" only has to be greater than 1px to then count. Could also use some callback properties, like `absX, absY`, and could limit a tap's "max"?

```
  const [tapped, setTap] = React.useState(false);
  const onTap = () => setTap(true);
  const handlers = useSwipeable({
    onSwiped: onTap,
    delta: 0,
  });
```

**Comment by tysonmatanich** [comment]
I was using it.

**Comment by tysonmatanich** [comment]
Also, these were not called out in the [v4 to v5 migration doc](https://github.com/dogfessional/react-swipeable/blob/master/migration.md). Use case is an image gallery carousel that besides allowing for right/left swipes also allows for a click which does the same as the left action. Hoping this functionality is added back.

**Comment by hartzis** [comment]
@tysonmatanich Thank you for letting me know. I'll explore getting `onTap` re-introduced. i think it should be straightforward and not add much to the bundled size.

`preventDefault` is actually still there as `preventDefaultTouchmoveEvent`, let me know if that is what you are looking for or if it was `stopPropagation`, which was removed.

**Comment by tysonmatanich** [comment]
@hartzis That would be great, thanks! Not sure why I had `stopPropagation`, must have misread something and assumed it was preventing default on the click/tap.

**Comment by hartzis** [comment]
Added back in with v6 release and #185 - https://github.com/FormidableLabs/react-swipeable/releases/tag/v6.0.0
