### ISSUE TITLE
deltaX is inverted

### ISSUE THREAD

**Issue by untitledlt** [FormidableLabs/react-swipeable#166]
**Describe the bug**
Swiping from left to right returns negative deltaX value.
That kinda feels inverted as other libs (f.e. hammer.js) returns positive.

Swiping from bottom to top produces positive deltaY value, so only X axis is inverted.

**Steps or Sandbox to reproduce**
https://codesandbox.io/s/react-swipeable-hook-deltax-inverted-f4net

**Expected behavior**
Swiping from left to right should produce positive deltaX and swiping from right to left should produce negative deltaX value.

** Device/Browser **
Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by hartzis** [comment]
Hey @untitledlt , thank you for the issue. I think this is related to #157 .

We updated the docs and we need to get #151 merged and released.

I'd like to see this standardized in the next major release, v6.

In the meantime does `absX` work for you?

**Comment by angrytoad** [comment]
Not OP but can confirm that i was terribly confused until I found this ticket.

I'm building a touch swipe component and ended up using the following to get the current X position within the component

`const currentX = eventData.initial[0] + eventData.absX;`

**Comment by hartzis** [comment]
Closing in favor of #157 to track progress
