### ISSUE TITLE
Test swiped function called enzyme/jest

### ISSUE THREAD

**Issue by romariolopezc** [FormidableLabs/react-swipeable#171]
Hello. I'm trying to test if a function is called on a swipe event. My function modifies the state and I want to test that is working as expected.

How can I fire a swipe event using this library?

**Comment by hartzis** [comment]
🤔 Great question. If you could create a [codesandbox.io](https://codesandbox.io/) example with tests I could really help out here. But i can throw out some ideas.

I'd try to mock the import with jest and then do a bait/switch type thing for the callback.
##### rough example

```
// Component to test
export const ComponentWithOnSwiped = ({ testFn }) => {
  const handler = useSwipeable({ onSwiped: testFn });
  return <div {...hanlder} />
}
```
```
// Test file
import { ComponentWithOnSwiped } from './component';
import { useSwipeable } from 'react-swipeable';

let currentOnSwiped;
jest.mock('react-swipeable', ()=>({
  useSwipeable: ({ onSwiped }) => { currentOnSwiped = onSwiped; },
})
...
it(' calls onSwipe callback', () => {
  const testFn = jest.fn();
  render(<ComponentWithOnSwiped />);

  // "Fire" react-swipeable's callback
  currentOnSwiped({ deltaX: 10, deltaY: 10 }) // or whatever event data you want
  expect(testFn).toHaveBeenCalledOnce();
})
```

**Comment by hartzis** [comment]
Please let me know if this worked or if you're able to get a codesandobx created. Please re-open if needed.

**Comment by justman00** [comment]
To leave a comment for somebody like me who was looking to do something similar.

Basically, the `react-swipeable` is using touch events under [the hood](https://github.com/FormidableLabs/react-swipeable/blob/main/src/index.ts#L104), hence we can trigger the `onSwiped` function just by firing some **touch events**:

```js
fireEvent.touchStart(firstSlide, {
  touches: [{ clientX: 0, clientY: 0 }]
});
fireEvent.touchMove(firstSlide, {
  touches: [{ clientX: -100, clientY: 23 }]
});
fireEvent.touchEnd(firstSlide);
```
The code above is using [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by hartzis** [comment]
^ Great example @justman00.

The tests also have great examples that use react testing library too.
https://github.com/FormidableLabs/react-swipeable/blob/ab5ca2ebd68eba997e3ba277c4e4514c192cc5e3/__tests__/useSwipeable.spec.tsx#L100-L115
