### ISSUE TITLE
eventHandler is not defined ?

### ISSUE THREAD

**Issue by PironSteve** [FormidableLabs/react-swipeable#176]
Hi, I'm currently trying to use react-swipeable  for my carousel to handle Swipe on mobile but i'm a beginner and I have a problem. Event Handler is undefined.
I don't understand what I'm supposed to do.

If it helps, here's where I use the package.

Thank you for your help.

`<Fade duration={5000}
          transitionDuration={500}
          infinite={true}
          indicators={true}
          scale={1}
          arrows={false}>
      {
        images.map((each, index) =>
          <Swipeable onSwiped={(eventData) => eventHandler} {...config} >
          <img key={index} alt={each} style={{width: '100%'}} src={each}/>
          </Swipeable>)
      }
    </Fade>`

**Comment by JoviDeCroock** [comment]
Hey seems like it's confused on this line

```
onSwiped={(eventData) => eventHandler}
```

You could for instance do this:

```
const eventHandler =  () => setState({
      swiped: true,
      swiping: false,
    });
```

**Comment by PironSteve** [comment]
Thank you for your answer,

I use nextjs which is a bit different from React and now it tells me that setState is not defined

If you want, i can post my component.

**Comment by JoviDeCroock** [comment]
My example was more meant to show you that it's you that decides on what's there, `setState` can refer to `this.setState` on a class component or `useState` on a Functional component.

**Comment by PironSteve** [comment]
I will try with a useState then. thank you for your advice
