### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking event

### ISSUE THREAD

**Issue by laclance** [FormidableLabs/react-swipeable#179]
using SwipeableHandlers causes:

```[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.```

and

```[Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.```

**Comment by hartzis** [comment]
Possibly related to #167 and #170

**Comment by laclance** [comment]
thanks
