### ISSUE TITLE
Add swipe events to document. 

### ISSUE THREAD

**Issue by chapster11** [FormidableLabs/react-swipeable#180]
I've been using the package and like it a lot. I was wondering if I'm missing anything in regards to been able to set the swipe events only on elements and not on a document. Or is it possible to add swipe events to document ? 

I read through some of the closed tickets and saw https://github.com/FormidableLabs/react-swipeable/issues/150 ticket which touches on the topic of using an element to detect the swipe from left but the problem is the element is above the content which prevents the content below it from been selectable. By setting the event on document would allow for editable content. 
The question was asked but not really answered in https://github.com/FormidableLabs/react-swipeable/issues/150. 

I can add my own event document.addEventListener('touchmove', touchMoveHandler)
but to save time I'd like to use this package if this is possible to have the events used on document as well as elements.

**Comment by hartzis** [comment]
@chapster11 I like this idea a lot!

It definitely has some overlap and carries some of the same concerns issues with #167 , #170 , #179 .

We need to figure out our approach for "passive event options" for [v6](https://github.com/FormidableLabs/react-swipeable/projects/2).

___

**But** we could attempt to implement this for `v5` if you had an interest.

I really like how `react-use-gesture` solved this using [`domTarget` prop](https://use-gesture.netlify.app/docs/options#domtarget)

We additionally have a helper that could be modified/updated to incorporate this prop for both touch and mouse handlers.
https://github.com/FormidableLabs/react-swipeable/blob/939ee9fdbc108e07af4ac1dfc5739f2db1a6f7d4/src/index.js#L138-L146

**Comment by merrywhether** [comment]
I have this library working on the document with the following pattern:

```ts
  const { ref } = useSwipeable({
    onSwiped: ({ dir }) => inputHandler.onSwipe(dir),
    preventDefaultTouchmoveEvent: true,
  }) as { ref: RefCallback<Document> };

  useEffect(() => {
    ref(document);
  });
```
Kind of hacky, but is working so far!

**Comment by hartzis** [comment]
I like the above solution. It works and doesn't require an overhaul to `react-swipeable`. I made a note to document this example in the README. Thank you you @merrywhether !
