### ISSUE TITLE
Create clickable thumbnails

### ISSUE THREAD

**Issue by Koli14** [FormidableLabs/react-swipeable#181]
I created a 'working' example, of what I want to achieve, although the effect of the sliding after a thumbnail click is terrible at the moment:
https://codesandbox.io/s/react-swipeable-with-thumbnails-nw4yp
I'm beginner with react. Did somebody achieved something like this before? 
Any suggestions, how to improve the behavior of my codeSandbox? 
I believe it must interest a lot of people.

**Comment by hartzis** [comment]
@Koli14 Not exactly sure what you're trying to achieve exactly. I do appreciate the codesandbox example creation, but having a hard time interpreting your desired outcome.

If I may suggest an actual image carousel library https://github.com/xiaolin/react-image-gallery

This package uses `react-swipeable` under the hood and may help you with what you're ultimately trying to achieve.

**Comment by hartzis** [comment]
Going to close for now, but feel free to open re-open if you think your issue is specific to `react-swipeable`.
