### ISSUE TITLE
It is not clear how to use ref from docs

### ISSUE THREAD

**Issue by Okami92** [FormidableLabs/react-swipeable#189]
Hi. I use hook version of swipeable and my ref on component doesn't work after I added swipeable event to div. From docs it is not very clear how to use innerRef. Is it suppose to be part of config inside useSwipeable object? I am adding this prop as part of config and it doesn't work.

**Comment by hartzis** [comment]
@Okami92 Great callout.

Couple things to note here.
- the `handlers` that `useSwipeable` returns include a `ref` prop that it uses internally to attach event listeners too
  - https://github.com/FormidableLabs/react-swipeable#hook-details
      - additionally `handlers` can have an `onMouseDown` prop if you're tracking mouse via `trackMouse` config
  - `innerRef` is a prop **only** used by the component
      - `<Swipeable innerRef={(el) => console.log('ref-', el)} />`

#### Explanation example:
```
const MyComponent = () => {

  // handlers here is an object that has a prop ref: `{ ref: refCallback }`
  const handlers = useSwipeable({ onSwiped: () => console.log('swiped') })

  // by spreading the handlers, this div now has a ref prop that `useSwipeable` uses internally
  return (<div { ...handlers } />
}
```

### passthrough access
If you'd like to additionally have access to the same ref/el you can do a passthrough sort of thing.
#### Example ref passthrough:
```
const MyComponent = () => {
  const handlers = useSwipeable({ onSwiped: () => console.log('swiped') })

  // setup ref for your usage
  const myRef = React.useRef();

  const refPassthrough = (el) => {
    // call useSwipeables ref prop with el    
    handlers.ref(el);
    // set the el to a ref you can access yourself
    myRef.current = el;
  }

  return (<div ref={refPassthrough} />
}
```

I'll try to work on clarifying this in the docs and call it out better for `v6` for sure.

Please let me know if this helps and if you have ideas or would like to make a PR to make the docs more clear.
Cheers.

**Comment by hartzis** [comment]
Want to add this to the v6 README FAQ section

**Comment by hartzis** [comment]
[example added to main readme](https://github.com/FormidableLabs/react-swipeable#how-to-share-ref-from-useswipeable) with #185 and v6 release
