### ISSUE TITLE
Convert velocity into a vector

### ISSUE THREAD

**Issue by upatel32** [FormidableLabs/react-swipeable#201]
verify "velocity" is accurate and document change/improvement if found

- https://github.com/react-spring/react-use-gesture/blob/02a39881f5bf940db09a527ce99c2a7069d07b42/src/utils/math.ts#L10-L20

**Comment by hartzis** [comment]
Closed with #185 - https://github.com/FormidableLabs/react-swipeable/releases/tag/v6.0.0
