### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by dappsar** [FormidableLabs/react-swipeable#205]
**Describe the bug**
Received warning:
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event in attachTouch function, because component is not specifying Passive event listeners.

**Potential solution **

Change this:
`
      tls.forEach(([e, h]) => el.addEventListener(e, h))
`

by this:
`
      tls.forEach(([e, h]) => el.addEventListener(e, h, { passive: true }))
`

in this code:
`
  const attachTouch = el => {
    if (el && el.addEventListener) {
      // attach touch event listeners and handlers
      const tls = [[touchStart, onStart], [touchMove, onMove], [touchEnd, onEnd]]
      tls.forEach(([e, h]) => el.addEventListener(e, h, { passive: true }))
      // return properly scoped cleanup method for removing listeners
      return () => tls.forEach(([e, h]) => el.removeEventListener(e, h))
    }
  }
`

** Device/Browser **
chrome > 51

**Additional context**
Passive event listeners are an emerging web standard, new feature shipped in Chrome 51 that provide a major potential boost to scroll performance. [Chrome Release Notes](https://blog.chromium.org/2016/05/new-apis-to-help-developers-improve.html). 

Problem:
All modern browsers have a threaded scrolling feature to permit scrolling to run smoothly even when expensive JavaScript is running, but this optimization is partially defeated by the need to wait for the results of any touchstart and touchmove handlers, which may prevent the scroll entirely by calling preventDefault() on the event.

Solution:
{passive: true}
By marking a touch or wheel listener as passive, the developer is promising the handler won't call preventDefault to disable scrolling. This frees the browser up to respond to scrolling immediately without waiting for JavaScript, thus ensuring a reliably smooth scrolling experience for the user.

[Demo VIdeo](https://www.youtube.com/watch?v=NPM6172J22g)
[Explainer Doc](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

**Comment by hartzis** [comment]
@dappsar thanks for the great write up and video!

It definitely has some overlap and carries some of the same concerns with issues #167 , #170 , #179 .

We are very aware of this issue and are working towards a solution in v6.

Would love to hear any thoughts on a best approach, please post to the above issues.

**Comment by hartzis** [comment]
Marked as duplicate and closing.

**Comment by hartzis** [comment]
@dappsar we have a tentative solution matching this solution pretty much exactly. Thank you again for your suggestion.

https://github.com/FormidableLabs/react-swipeable/pull/210
