### ISSUE TITLE
Demo website is broken

### ISSUE THREAD

**Issue by Brianzchen** [FormidableLabs/react-swipeable#212]
**Describe the bug**
The demo page http://stack.formidable.com/react-swipeable/ doesn't work

**Steps or Sandbox to reproduce**
Go to http://stack.formidable.com/react-swipeable/

**Expected behavior**
It should work

**Comment by maaznadeem246** [comment]
Yes demo website is not working 
when will demo website be working

**Comment by hartzis** [comment]
@Brianzchen and @maaznadeem246 Thank you for the heads up and issue.

@formidableLabs recently changed some github settings and the URL apparently changed, apologies.

The new URL:
- http://formidablelabs.github.io/react-swipeable/

I've updated the link on the github page.

**Comment by hartzis** [comment]
Actually going to leave open till i have time to publish a bug fix for v5 that has the right URL for npm

**Comment by hartzis** [comment]
Actually actually, v6 is about to come out, dont want to republish just for the readme change.
