### ISSUE TITLE
props[onSwipedDir] is not a function

### ISSUE THREAD

**Issue by ArtemAstakhov** [FormidableLabs/react-swipeable#217]
**Describe the bug**
Library drops error if hook callback is undefined

**Steps or Sandbox to reproduce**
```
const handlers = useSwipeable({
    onSwipedDown: open ? onClose : undefined,
});
```

**Comment by cwise89** [comment]
@ArtemAstakhov Thanks for checking out react-swipable! What you're experiencing is an expected error. Might I suggest this implementation? I confirmed it works ;)

```
  const handlers = useSwipeable({
    ...(open && { onSwipedDown: onClose })
  });
```
