### ISSUE TITLE
Upgrade to Typescript 4

### ISSUE THREAD

**Issue by hartzis** [FormidableLabs/react-swipeable#220]
Look into upgrading to typescript 4.
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html

- [x] check if `microbundle` supports ts 4
  - https://www.npmjs.com/package/microbundle
  - ✅  https://github.com/developit/microbundle/pull/738

**Comment by cwise89** [comment]
@hartzis, I'm starting on this today. From my initial research on this, Typescript 4 docs describe this as a non-breaking change. I can't seem to find any relevant information from microbundle in regards to explicit compatible versions of  typescript. I'm going to just try and update to TS4 and test build. Any other concerns to bee aware of? 
~Cheers
