### ISSUE TITLE
onSwiping first is always true

### ISSUE THREAD

**Issue by feketegy** [FormidableLabs/react-swipeable#221]
**Describe the bug**
The `first` property for the onSwiping event is always true, not just for the first event.

**Steps or Sandbox to reproduce**
Fork the example codesandbox:
- https://codesandbox.io/s/react-swipeable-image-carousel-forked-ckgc8?file=/src/index.js

**Expected behavior**
The `first` property should be true on the very first event and false on subsequent events.

** Device/Browser **
Latest Chrome.

**Comment by hartzis** [comment]
@feketegy Great find, thank you for the creating an issue and example, i appreciate it!

I thought we had a test for this, but alas we do not.

I'll see if i can get a PR open for a fix soon.

**Comment by hartzis** [comment]
Fixed with #223 and published version `v6.0.1`
