### ISSUE TITLE
Expose swipe start?

### ISSUE THREAD

**Issue by feketegy** [FormidableLabs/react-swipeable#222]
Why not expose the `touchStart / mouseDown` events so users can separate out the very first swipe, instead of connecting it to the `onSwiping` event's `first` property?

**Comment by hartzis** [comment]
@feketegy sensible question, 🤔 . I'm curious what that could look like.

Any thoughts or ideas?

**Comment by feketegy** [comment]
@hartzis My specific use case would be to set up some states on the very first swipe event, I'm using your package more like a dragging & dropping library :)

This is why I was relying on the `first` property being true, but it has this bug: https://github.com/FormidableLabs/react-swipeable/issues/221

I think it would be cleaner this way to expose an `onSwipeStart` event rather to rely on the `first` property in the `onSwiping` callback.

Great package btw 👍

**Comment by hartzis** [comment]
@feketegy Great suggestion. I think `onSwipeStart` is simple and small enough to introduce.

Thoughts on #226 as a solution?

**Comment by feketegy** [comment]
I totally missed this, awesome addition, thanks for this!
