### ISSUE TITLE
Duplicated eventlistener? 

### ISSUE THREAD

**Issue by ash0080** [FormidableLabs/react-swipeable#229]
**Describe the bug**
![duplicated](https://user-images.githubusercontent.com/2803210/105042354-198e7b00-5a9f-11eb-9d74-8c60ce9044df.gif)

**Steps or Sandbox to reproduce**
open your app in browser, switch to another tab(browser tabs) then back, ( or wait a few minutes )
It looks like hook re-add another eventListener (duplicated)
switch and back... 3. then 4

**Expected behavior**
The current cleanup policy seems does not work 100% of the time

** Device/Browser **
chrome, safari, ios safari

Passive or active mode are the same

My code is almost identical to the example, except that I used preact and styled component

**Comment by hartzis** [comment]
@ash0080 Thank you for submitting the issue. This is a very intriguing bug and I'd love to help dig into replicating and fixing it.

When you say "almost identical to the example" do you mean the codesandbox.io example [here](https://codesandbox.io/s/react-swipeable-image-carousel-hben8?file=/src/Carousel.js)?

If so i'm unable to replicate what you're seeing by waiting and switching between tabs with the above codesandbox example.

Could you share your codesandbox that you've created and I'll see if i can replicate it with your example?

**Comment by hartzis** [comment]
closing for now, please re-open if we can get an example 😸
