### ISSUE TITLE
Element.setCapture() is deprecated.

### ISSUE THREAD

**Issue by car1ot** [FormidableLabs/react-swipeable#270]
Hello.
I am using this package with React app.
On Mozilla Firefox browser, got warning in console: ```Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture```.

I am using ```"react-swipeable": "^6.2.0",``` version.

**Comment by hartzis** [comment]
@car1ot Could you setup a reproducible example with `react-swipeable` showing this error by chance?

I'm unable to replicate this in firefox with the examples.

And to note we do not utilize pointer events nor `setCapture` or `setPointerCapture` in our codebase.

If you're able to narrow it to `react-swipeable` with an example please re-open and i'll gladly take a look to see how we can fix this warning.

cheers

**Comment by Harmouch101** [comment]
The issue is not related to this package; It is a firefox issue as i discovered before filing this issue([webcompat/web-bugs/issues/107300](https://github.com/webcompat/web-bugs/issues/107300)) while testing the responsiveness of a website i was working on.

**Comment by hartzis** [comment]
@Harmouch101 Thank you for adding additional info!
