### ISSUE TITLE
prevent swipe 

### ISSUE THREAD

**Issue by leineveber** [FormidableLabs/react-swipeable#274]
Hey, I have a global swipe event (onSwipedLeft) on a document that makes some logic. On the page I also have a carousel. When I'm swiping carousel it also triggers global swipe event. How can I prevent it only on carousels or etc things?

**Comment by patrickkfkan** [comment]
I came across a similar situation where I had a slider instead of carousel. Here's my workaround:
1. Add a 'no-swipe' class to the components that I don't want the global swipe event to trigger
2. The global swipe event will still trigger but inside the swipe handler I check whether the event path contains an element with the 'no-swipe' class. If so, ignore the swipe.

Example:
https://codesandbox.io/s/crazy-gould-meuek?file=/src/App.js

(I'm new to React, so this might not be the proper way of doing it)

**Comment by leineveber** [comment]
> *

It works! Thank you a lot!

**Comment by leineveber** [comment]
> I came across a similar situation where I had a slider instead of carousel. Here's my workaround:
> 
> 1. Add a 'no-swipe' class to the components that I don't want the global swipe event to trigger
> 2. The global swipe event will still trigger but inside the swipe handler I check whether the event path contains an element with the 'no-swipe' class. If so, ignore the swipe.
> 
> Example: https://codesandbox.io/s/crazy-gould-meuek?file=/src/App.js
> 
> (I'm new to React, so this might not be the proper way of doing it)

Thank you a lot, it works!

**Comment by hartzis** [comment]
@leineveber I was able to create a codesandbox that utilizes [Event.stopPropagation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) as a means to stop the nested swipe events from reaching the document swipe handlers.

Open this on a mobile device or with dev tools mobile view to see it in action.

https://codesandbox.io/s/react-swipeable-document-swipe-example-1yvr2v?file=/src/index.js:407-545

![doc_swipe2](https://user-images.githubusercontent.com/5378707/155463656-536f07be-44b6-4fcc-9336-ad9a0341dbd7.gif)

**Comment by Edjevw12** [comment]
> I came across a similar situation where I had a slider instead of carousel. Here's my workaround:
> 
> 1. Add a 'no-swipe' class to the components that I don't want the global swipe event to trigger
> 2. The global swipe event will still trigger but inside the swipe handler I check whether the event path contains an element with the 'no-swipe' class. If so, ignore the swipe.
> 
> Example: https://codesandbox.io/s/crazy-gould-meuek?file=/src/App.js
> 
> (I'm new to React, so this might not be the proper way of doing it)

I had a similar issue, with my capacitor app. Since iOS/Safari webview is not supporting `path` I implemented it like this:

```js
//this function checks if the swipe was on a slider, by looping through the (parent) element nodes
function checkIfSwipedOnSlider({ node }: { node: HTMLElement }) {
  let parent = node

  while (parent) {
    const className =
      parent?.className && typeof parent.className === 'string' ? parent.className : null

    if (className && className.match(/slick-slide|slider-container/)) return true
    
    // abort loop when reached <Layout /> component
    if (className && className.match(/layout.css-18jqfyr/)) return false
    parent = parent.parentElement
  }
  return false
}
```

I throttled my handler, to avoid some performance bottlenecks.

```js
  import throttle from 'lodash/throttle'

  const throttleOnSwipeHandler = useMemo(() => {
    return throttle((event: SwipeEventData) => {
      const isSwipedOnSlider = checkIfSwipedOnSlider({ node: event.event.target as HTMLElement })

      if (isSwipedOnSlider) return
      ...

    }, 200)
  }, [...])
```


Then we call it like this :)

```js
  const { ref } = useSwipeable({
    onSwiped: (e) => {
      if (e.dir === 'Up' || e.dir === 'Down') return
      throttleOnSwipeHandler(e)
    },

    delta: {
      right: 20,
      left: 20,
    },
    // trackMouse: false,
    preventDefaultTouchmoveEvent: false,
  })
```

**Comment by hartzis** [comment]
Multiple solutions provided.

Additionally please check out [v7.0.0](https://github.com/FormidableLabs/react-swipeable/releases/tag/v7.0.0) and the new props to see if they can help out now.
- https://github.com/FormidableLabs/react-swipeable#toucheventoptions
