### ISSUE TITLE
Pee dependencies error when using it with react 18

### ISSUE THREAD

**Issue by Yasser-Belatreche** [FormidableLabs/react-swipeable#305]
**Describe the bug**
i just upgrade into react 18 and npm raise a peer dependency conflict error with the react-swipeable@6.2.1

**Expected behavior**
react-swipeable add the support for react 18

** Device/Browser **
OS : windows 11
node version : v16.14.0
npm version : 8.6.0 

**Additional context**
Here is a screenshot of the 
![Screenshot (20)](https://user-images.githubusercontent.com/79541979/164701297-92797453-ddec-4d3a-9f97-86ffe4e1526f.png)

**Comment by hartzis** [comment]
@Yasser-Belatreche released [v6.2.2](https://github.com/FormidableLabs/react-swipeable/releases/tag/v6.2.2) and [v7.0.0](https://github.com/FormidableLabs/react-swipeable/releases/tag/v7.0.0), both have react v18 peer dep 😸 🥂 🎉
