### ISSUE TITLE
trackMouse not working

### ISSUE THREAD

**Issue by janwirth** [FormidableLabs/react-swipeable#334]
**Describe the bug**
Mouse events are not registered despite trackMouse being enabled

**Steps or Sandbox to reproduce**

[- https://codesandbox.io/s/react-swipeable-image-carousel-hben8](https://codesandbox.io/s/react-swipeable-image-carousel-forked-3mxp8s)

**Expected behavior**
Mouse events trigger swipe

** Device/Browser **
Chrome 117.0.5938.149 am64 
MacOS 13.4 (22F2063)

**Comment by hartzis** [comment]
I suspect the issue to be how you're missing spreading some props.

in your example you're only using the `ref`, when you should be spreading **all** props from `useSwipeable`

```diff
- const { ref } = useSwipeable({
+ const handlers = useSwipeable({
...
<div {...handlers}>
```

fyi please refer to the readme/docs

https://github.com/FormidableLabs/react-swipeable#api

**Comment by sian022** [comment]
@hartzis solution worked! thanks!

**Comment by janwirth** [comment]
Not using it anymore, closing this issue. Thanks for the info @hartzis
